// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/ricleal/twitter-clone/internal/service/repository/postgres/models"
)

type Factory struct {
	baseSchemaMigrationMods SchemaMigrationModSlice
	baseTweetMods           TweetModSlice
	baseUserMods            UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewSchemaMigration(mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	return f.NewSchemaMigrationWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaMigrationWithContext(ctx context.Context, mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(ctx, o)
	}

	SchemaMigrationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaMigration(m *models.SchemaMigration) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f, alreadyPersisted: true}

	o.Version = func() int64 { return m.Version }
	o.Dirty = func() bool { return m.Dirty }

	return o
}

func (f *Factory) NewTweet(mods ...TweetMod) *TweetTemplate {
	return f.NewTweetWithContext(context.Background(), mods...)
}

func (f *Factory) NewTweetWithContext(ctx context.Context, mods ...TweetMod) *TweetTemplate {
	o := &TweetTemplate{f: f}

	if f != nil {
		f.baseTweetMods.Apply(ctx, o)
	}

	TweetModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingTweet(m *models.Tweet) *TweetTemplate {
	o := &TweetTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.UserID = func() string { return m.UserID }
	o.Content = func() string { return m.Content }
	o.DeletedAt = func() null.Val[time.Time] { return m.DeletedAt }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.User != nil {
		TweetMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Username = func() string { return m.Username }
	o.Email = func() string { return m.Email }
	o.Name = func() null.Val[string] { return m.Name }
	o.DeletedAt = func() null.Val[time.Time] { return m.DeletedAt }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.Tweets) > 0 {
		UserMods.AddExistingTweets(m.R.Tweets...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}

func (f *Factory) ClearBaseTweetMods() {
	f.baseTweetMods = nil
}

func (f *Factory) AddBaseTweetMod(mods ...TweetMod) {
	f.baseTweetMods = append(f.baseTweetMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
