// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/ricleal/twitter-clone/internal/service/repository/postgres/models"
	"github.com/stephenafamo/bob"
)

type TweetMod interface {
	Apply(context.Context, *TweetTemplate)
}

type TweetModFunc func(context.Context, *TweetTemplate)

func (f TweetModFunc) Apply(ctx context.Context, n *TweetTemplate) {
	f(ctx, n)
}

type TweetModSlice []TweetMod

func (mods TweetModSlice) Apply(ctx context.Context, n *TweetTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TweetTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TweetTemplate struct {
	ID        func() string
	UserID    func() string
	Content   func() string
	DeletedAt func() null.Val[time.Time]
	CreatedAt func() null.Val[time.Time]
	UpdatedAt func() null.Val[time.Time]

	r tweetR
	f *Factory

	alreadyPersisted bool
}

type tweetR struct {
	User *tweetRUserR
}

type tweetRUserR struct {
	o *UserTemplate
}

// Apply mods to the TweetTemplate
func (o *TweetTemplate) Apply(ctx context.Context, mods ...TweetMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Tweet
// according to the relationships in the template. Nothing is inserted into the db
func (t TweetTemplate) setModelRels(o *models.Tweet) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Tweets = append(rel.R.Tweets, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.TweetSetter
// this does nothing with the relationship templates
func (o TweetTemplate) BuildSetter() *models.TweetSetter {
	m := &models.TweetSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Content != nil {
		val := o.Content()
		m.Content = omit.From(val)
	}
	if o.DeletedAt != nil {
		val := o.DeletedAt()
		m.DeletedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.TweetSetter
// this does nothing with the relationship templates
func (o TweetTemplate) BuildManySetter(number int) []*models.TweetSetter {
	m := make([]*models.TweetSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Tweet
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TweetTemplate.Create
func (o TweetTemplate) Build() *models.Tweet {
	m := &models.Tweet{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Content != nil {
		m.Content = o.Content()
	}
	if o.DeletedAt != nil {
		m.DeletedAt = o.DeletedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TweetSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TweetTemplate.CreateMany
func (o TweetTemplate) BuildMany(number int) models.TweetSlice {
	m := make(models.TweetSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTweet(m *models.TweetSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "36")
		m.UserID = omit.From(val)
	}
	if !(m.Content.IsValue()) {
		val := random_string(nil)
		m.Content = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Tweet
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TweetTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Tweet) error {
	var err error

	return err
}

// Create builds a tweet and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TweetTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Tweet, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTweet(opt)

	if o.r.User == nil {
		TweetMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Tweets.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a tweet and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TweetTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Tweet {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a tweet and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TweetTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Tweet {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple tweets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TweetTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TweetSlice, error) {
	var err error
	m := make(models.TweetSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple tweets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TweetTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TweetSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple tweets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TweetTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TweetSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Tweet has methods that act as mods for the TweetTemplate
var TweetMods tweetMods

type tweetMods struct{}

func (m tweetMods) RandomizeAllColumns(f *faker.Faker) TweetMod {
	return TweetModSlice{
		TweetMods.RandomID(f),
		TweetMods.RandomUserID(f),
		TweetMods.RandomContent(f),
		TweetMods.RandomDeletedAt(f),
		TweetMods.RandomCreatedAt(f),
		TweetMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m tweetMods) ID(val string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m tweetMods) IDFunc(f func() string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetID() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m tweetMods) RandomID(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m tweetMods) UserID(val string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m tweetMods) UserIDFunc(f func() string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetUserID() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m tweetMods) RandomUserID(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UserID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m tweetMods) Content(val string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.Content = func() string { return val }
	})
}

// Set the Column from the function
func (m tweetMods) ContentFunc(f func() string) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.Content = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetContent() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.Content = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m tweetMods) RandomContent(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.Content = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m tweetMods) DeletedAt(val null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.DeletedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m tweetMods) DeletedAtFunc(f func() null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.DeletedAt = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetDeletedAt() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.DeletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m tweetMods) RandomDeletedAt(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m tweetMods) RandomDeletedAtNotNull(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m tweetMods) CreatedAt(val null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m tweetMods) CreatedAtFunc(f func() null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetCreatedAt() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m tweetMods) RandomCreatedAt(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m tweetMods) RandomCreatedAtNotNull(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m tweetMods) UpdatedAt(val null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m tweetMods) UpdatedAtFunc(f func() null.Val[time.Time]) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m tweetMods) UnsetUpdatedAt() TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m tweetMods) RandomUpdatedAt(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m tweetMods) RandomUpdatedAtNotNull(f *faker.Faker) TweetMod {
	return TweetModFunc(func(_ context.Context, o *TweetTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m tweetMods) WithParentsCascading() TweetMod {
	return TweetModFunc(func(ctx context.Context, o *TweetTemplate) {
		if isDone, _ := tweetWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = tweetWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m tweetMods) WithUser(rel *UserTemplate) TweetMod {
	return TweetModFunc(func(ctx context.Context, o *TweetTemplate) {
		o.r.User = &tweetRUserR{
			o: rel,
		}
	})
}

func (m tweetMods) WithNewUser(mods ...UserMod) TweetMod {
	return TweetModFunc(func(ctx context.Context, o *TweetTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m tweetMods) WithExistingUser(em *models.User) TweetMod {
	return TweetModFunc(func(ctx context.Context, o *TweetTemplate) {
		o.r.User = &tweetRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m tweetMods) WithoutUser() TweetMod {
	return TweetModFunc(func(ctx context.Context, o *TweetTemplate) {
		o.r.User = nil
	})
}
