// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SchemaMigrations = Table[
	schemaMigrationColumns,
	schemaMigrationIndexes,
	schemaMigrationForeignKeys,
	schemaMigrationUniques,
	schemaMigrationChecks,
]{
	Schema: "",
	Name:   "schema_migrations",
	Columns: schemaMigrationColumns{
		Version: column{
			Name:      "version",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Dirty: column{
			Name:      "dirty",
			DBType:    "boolean",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: schemaMigrationIndexes{
		SchemaMigrationsPkey: index{
			Type: "btree",
			Name: "schema_migrations_pkey",
			Columns: []indexColumn{
				{
					Name:         "version",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "schema_migrations_pkey",
		Columns: []string{"version"},
		Comment: "",
	},

	Comment: "",
}

type schemaMigrationColumns struct {
	Version column
	Dirty   column
}

func (c schemaMigrationColumns) AsSlice() []column {
	return []column{
		c.Version, c.Dirty,
	}
}

type schemaMigrationIndexes struct {
	SchemaMigrationsPkey index
}

func (i schemaMigrationIndexes) AsSlice() []index {
	return []index{
		i.SchemaMigrationsPkey,
	}
}

type schemaMigrationForeignKeys struct{}

func (f schemaMigrationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type schemaMigrationUniques struct{}

func (u schemaMigrationUniques) AsSlice() []constraint {
	return []constraint{}
}

type schemaMigrationChecks struct{}

func (c schemaMigrationChecks) AsSlice() []check {
	return []check{}
}
