// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tweets = Table[
	tweetColumns,
	tweetIndexes,
	tweetForeignKeys,
	tweetUniques,
	tweetChecks,
]{
	Schema: "",
	Name:   "tweets",
	Columns: tweetColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Content: column{
			Name:      "content",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeletedAt: column{
			Name:      "deleted_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: tweetIndexes{
		TweetsPkey: index{
			Type: "btree",
			Name: "tweets_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "tweets_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: tweetForeignKeys{
		TweetsTweetsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "tweets.tweets_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type tweetColumns struct {
	ID        column
	UserID    column
	Content   column
	DeletedAt column
	CreatedAt column
	UpdatedAt column
}

func (c tweetColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Content, c.DeletedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type tweetIndexes struct {
	TweetsPkey index
}

func (i tweetIndexes) AsSlice() []index {
	return []index{
		i.TweetsPkey,
	}
}

type tweetForeignKeys struct {
	TweetsTweetsUserIDFkey foreignKey
}

func (f tweetForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TweetsTweetsUserIDFkey,
	}
}

type tweetUniques struct{}

func (u tweetUniques) AsSlice() []constraint {
	return []constraint{}
}

type tweetChecks struct{}

func (c tweetChecks) AsSlice() []check {
	return []check{}
}
