version: "3.7"
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    environment:
      DB_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@host.docker.internal:${DB_PORT}/${DB_NAME}?sslmode=disable"
      LOG_LEVEL: ${LOG_LEVEL}
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
