services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL_API_DEV}
      LOG_LEVEL: ${LOG_LEVEL}
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
