// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	SchemaMigrations schemaMigrationWhere[Q]
	Tweets           tweetWhere[Q]
	Users            userWhere[Q]
} {
	return struct {
		SchemaMigrations schemaMigrationWhere[Q]
		Tweets           tweetWhere[Q]
		Users            userWhere[Q]
	}{
		SchemaMigrations: buildSchemaMigrationWhere[Q](SchemaMigrations.Columns),
		Tweets:           buildTweetWhere[Q](Tweets.Columns),
		Users:            buildUserWhere[Q](Users.Columns),
	}
}
