// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Tweet is an object representing the database table.
type Tweet struct {
	ID        string              `db:"id,pk" `
	UserID    string              `db:"user_id" `
	Content   string              `db:"content" `
	DeletedAt null.Val[time.Time] `db:"deleted_at" `
	CreatedAt null.Val[time.Time] `db:"created_at" `
	UpdatedAt null.Val[time.Time] `db:"updated_at" `

	R tweetR `db:"-" `
}

// TweetSlice is an alias for a slice of pointers to Tweet.
// This should almost always be used instead of []*Tweet.
type TweetSlice []*Tweet

// Tweets contains methods to work with the tweets table
var Tweets = psql.NewTablex[*Tweet, TweetSlice, *TweetSetter]("", "tweets", buildTweetColumns("tweets"))

// TweetsQuery is a query on the tweets table
type TweetsQuery = *psql.ViewQuery[*Tweet, TweetSlice]

// tweetR is where relationships are stored.
type tweetR struct {
	User *User // tweets.tweets_user_id_fkey
}

func buildTweetColumns(alias string) tweetColumns {
	return tweetColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "content", "deleted_at", "created_at", "updated_at",
		).WithParent("tweets"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Content:    psql.Quote(alias, "content"),
		DeletedAt:  psql.Quote(alias, "deleted_at"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type tweetColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Content    psql.Expression
	DeletedAt  psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c tweetColumns) Alias() string {
	return c.tableAlias
}

func (tweetColumns) AliasedAs(alias string) tweetColumns {
	return buildTweetColumns(alias)
}

// TweetSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TweetSetter struct {
	ID        omit.Val[string]        `db:"id,pk" `
	UserID    omit.Val[string]        `db:"user_id" `
	Content   omit.Val[string]        `db:"content" `
	DeletedAt omitnull.Val[time.Time] `db:"deleted_at" `
	CreatedAt omitnull.Val[time.Time] `db:"created_at" `
	UpdatedAt omitnull.Val[time.Time] `db:"updated_at" `
}

func (s TweetSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Content.IsValue() {
		vals = append(vals, "content")
	}
	if !s.DeletedAt.IsUnset() {
		vals = append(vals, "deleted_at")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TweetSetter) Overwrite(t *Tweet) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Content.IsValue() {
		t.Content = s.Content.MustGet()
	}
	if !s.DeletedAt.IsUnset() {
		t.DeletedAt = s.DeletedAt.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *TweetSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tweets.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Content.IsValue() {
			vals[2] = psql.Arg(s.Content.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.DeletedAt.IsUnset() {
			vals[3] = psql.Arg(s.DeletedAt.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[4] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.UpdatedAt.IsUnset() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TweetSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TweetSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Content.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if !s.DeletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "deleted_at")...),
			psql.Arg(s.DeletedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTweet retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTweet(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Tweet, error) {
	if len(cols) == 0 {
		return Tweets.Query(
			sm.Where(Tweets.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tweets.Query(
		sm.Where(Tweets.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tweets.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TweetExists checks the presence of a single record by primary key
func TweetExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Tweets.Query(
		sm.Where(Tweets.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Tweet is retrieved from the database
func (o *Tweet) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tweets.AfterSelectHooks.RunHooks(ctx, exec, TweetSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tweets.AfterInsertHooks.RunHooks(ctx, exec, TweetSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tweets.AfterUpdateHooks.RunHooks(ctx, exec, TweetSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tweets.AfterDeleteHooks.RunHooks(ctx, exec, TweetSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Tweet
func (o *Tweet) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Tweet) pkEQ() dialect.Expression {
	return psql.Quote("tweets", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Tweet
func (o *Tweet) Update(ctx context.Context, exec bob.Executor, s *TweetSetter) error {
	v, err := Tweets.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Tweet record with an executor
func (o *Tweet) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tweets.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Tweet using the executor
func (o *Tweet) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tweets.Query(
		sm.Where(Tweets.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TweetSlice is retrieved from the database
func (o TweetSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tweets.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tweets.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tweets.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tweets.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TweetSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tweets", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TweetSlice) copyMatchingRows(from ...*Tweet) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TweetSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tweets.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tweet:
				o.copyMatchingRows(retrieved)
			case []*Tweet:
				o.copyMatchingRows(retrieved...)
			case TweetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tweet or a slice of Tweet
				// then run the AfterUpdateHooks on the slice
				_, err = Tweets.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TweetSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tweets.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tweet:
				o.copyMatchingRows(retrieved)
			case []*Tweet:
				o.copyMatchingRows(retrieved...)
			case TweetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tweet or a slice of Tweet
				// then run the AfterDeleteHooks on the slice
				_, err = Tweets.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TweetSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TweetSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tweets.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TweetSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tweets.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TweetSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tweets.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Tweet) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os TweetSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTweetUser0(ctx context.Context, exec bob.Executor, count int, tweet0 *Tweet, user1 *User) (*Tweet, error) {
	setter := &TweetSetter{
		UserID: omit.From(user1.ID),
	}

	err := tweet0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTweetUser0: %w", err)
	}

	return tweet0, nil
}

func (tweet0 *Tweet) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTweetUser0(ctx, exec, 1, tweet0, user1)
	if err != nil {
		return err
	}

	tweet0.R.User = user1

	user1.R.Tweets = append(user1.R.Tweets, tweet0)

	return nil
}

func (tweet0 *Tweet) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachTweetUser0(ctx, exec, 1, tweet0, user1)
	if err != nil {
		return err
	}

	tweet0.R.User = user1

	user1.R.Tweets = append(user1.R.Tweets, tweet0)

	return nil
}

type tweetWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	UserID    psql.WhereMod[Q, string]
	Content   psql.WhereMod[Q, string]
	DeletedAt psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereNullMod[Q, time.Time]
	UpdatedAt psql.WhereNullMod[Q, time.Time]
}

func (tweetWhere[Q]) AliasedAs(alias string) tweetWhere[Q] {
	return buildTweetWhere[Q](buildTweetColumns(alias))
}

func buildTweetWhere[Q psql.Filterable](cols tweetColumns) tweetWhere[Q] {
	return tweetWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		UserID:    psql.Where[Q, string](cols.UserID),
		Content:   psql.Where[Q, string](cols.Content),
		DeletedAt: psql.WhereNull[Q, time.Time](cols.DeletedAt),
		CreatedAt: psql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Tweet) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("tweet cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Tweets = TweetSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("tweet has no relationship %q", name)
	}
}

type tweetPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildTweetPreloader() tweetPreloader {
	return tweetPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Tweets,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type tweetThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTweetThenLoader[Q orm.Loadable]() tweetThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return tweetThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the tweet's User into the .R struct
func (o *Tweet) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tweets = TweetSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the tweet's User into the .R struct
func (os TweetSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Tweets = append(rel.R.Tweets, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type tweetJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j tweetJoins[Q]) aliasedAs(alias string) tweetJoins[Q] {
	return buildTweetJoins[Q](buildTweetColumns(alias), j.typ)
}

func buildTweetJoins[Q dialect.Joinable](cols tweetColumns, typ string) tweetJoins[Q] {
	return tweetJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
