// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Tweet defines model for Tweet.
type Tweet struct {
	Content string              `json:"content"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	User    openapi_types.UUID  `json:"user"`
}

// User defines model for User.
type User struct {
	Email    openapi_types.Email `json:"email"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	Name     *string             `json:"name,omitempty"`
	Username string              `json:"username"`
}

// PostTweetsJSONRequestBody defines body for PostTweets for application/json ContentType.
type PostTweetsJSONRequestBody = Tweet

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User
