// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	Content string              `json:"content"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	UserId  openapi_types.UUID  `json:"user_id"`
}

// User defines model for User.
type User struct {
	Email    openapi_types.Email `json:"email"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	Name     *string             `json:"name,omitempty"`
	Username string              `json:"username"`
}

// PostTweetsJSONRequestBody defines body for PostTweets for application/json ContentType.
type PostTweetsJSONRequestBody = Tweet

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User
