// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SchemaMigrationErrors = &schemaMigrationErrors{
	ErrUniqueSchemaMigrationsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "schema_migrations",
		columns: []string{"version"},
		s:       "schema_migrations_pkey",
	},
}

type schemaMigrationErrors struct {
	ErrUniqueSchemaMigrationsPkey *UniqueConstraintError
}
