// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TweetErrors = &tweetErrors{
	ErrUniqueTweetsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "tweets",
		columns: []string{"id"},
		s:       "tweets_pkey",
	},
}

type tweetErrors struct {
	ErrUniqueTweetsPkey *UniqueConstraintError
}
