// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	models "github.com/ricleal/twitter-clone/internal/service/repository/postgres/models"
	factory "github.com/ricleal/twitter-clone/internal/service/repository/postgres/models/factory"
	"github.com/stephenafamo/bob"
)

func TestUserUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.User) factory.UserModSlice
	}{
		{
			name:        "ErrUniqueUsersPkey",
			expectedErr: UserErrors.ErrUniqueUsersPkey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.User) factory.UserModSlice {
				shouldUpdate := false
				updateMods := make(factory.UserModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewUserWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.UserModSlice{
					factory.UserMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueUsersEmailKey",
			expectedErr: UserErrors.ErrUniqueUsersEmailKey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.User) factory.UserModSlice {
				shouldUpdate := false
				updateMods := make(factory.UserModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewUserWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.UserModSlice{
					factory.UserMods.Email(obj.Email),
				}
			},
		},
		{
			name:        "ErrUniqueUsersUsernameKey",
			expectedErr: UserErrors.ErrUniqueUsersUsernameKey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.User) factory.UserModSlice {
				shouldUpdate := false
				updateMods := make(factory.UserModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewUserWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.UserModSlice{
					factory.UserMods.Username(obj.Username),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewUserWithContext(ctx, factory.UserMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewUserWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewUserWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
