name: Unit, Integration and E2E tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      MIGRATIONS_PATH: ${{ github.workspace }}/migrations

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Runs Unit Tests
        run: make test

      - name: Runs Integration Tests
        run: make test_integration

      - name: Runs E2E Tests
        run: make test_e2e
