name: Unit, Integration and E2E tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:

    # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Runs Unit Tests
        run: make test

      - name: Runs Integration Tests
        run: make test_integration

      - name: Runs E2E Tests
        run: make test_e2e
